import React, { useEffect, useState } from "react";
import UserLayout from "../../components/user/UserLayout";
import Dropdown from "../../components/ui/Dropdown";
import Pagination from "../../components/ui/Pagination";
import { getSecuritySettingsApi, updateSecuritySettingsApi, changeSecurityPasswordApi, getSecuritySessionsApi, revokeSecuritySessionApi, getSecurityActivityApi } from "../../services/user/securityApi";
import { useDebounce } from "../../hooks/useDebounce";
import { queryClient } from "../../lib/queryClient";
import { ShieldCheck, Smartphone, Mail, KeyRound, BellRing, LogOut, LockKeyhole, CheckCircle2, AlertTriangle, RefreshCw, Search, MonitorSmartphone } from "lucide-react";

const initialSettings = { twoFactorEnabled:false, emailVerified:true, phoneVerified:true, loginAlerts:true, withdrawalConfirmation:true, sessionTimeout:"30 minutes", lastPasswordChange:"12 Sep 2026" };

export default function Security(){
  const [settings,setSettings]=useState(initialSettings); const [sessions,setSessions]=useState([]); const [activity,setActivity]=useState([]);
  const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [password,setPassword]=useState({currentPassword:"",newPassword:"",confirmPassword:""}); const [passwordOpen,setPasswordOpen]=useState(false); const [passwordMsg,setPasswordMsg]=useState("");
  const [search,setSearch]=useState(""); const debouncedSearch=useDebounce(search,400); const [status,setStatus]=useState("all"); const [page,setPage]=useState(1); const [limit,setLimit]=useState(10); const [total,setTotal]=useState(0); const totalPages=Math.max(1,Math.ceil(total/limit));

  const load=async(showSpinner=true)=>{ const controller=new AbortController(); if(showSpinner)setLoading(true);else setRefreshing(true);setError(""); try{const [s,ss,a]=await Promise.all([getSecuritySettingsApi(controller.signal),getSecuritySessionsApi(controller.signal),getSecurityActivityApi({search:debouncedSearch,status,page,limit},controller.signal)]); setSettings(s?.data??s??initialSettings); setSessions(ss?.data?.items??ss?.items??[]); const payload=a?.data??a??{};setActivity(payload.items??[]);setTotal(Number(payload.total??0));}catch(e){if(e?.name!=="AbortError")setError(e?.message||"Unable to load security settings.");}finally{setLoading(false);setRefreshing(false)} return ()=>controller.abort(); };
  useEffect(()=>{let active=true;const run=async()=>{const cleanup=await load(true);if(!active&&cleanup)cleanup()};run();return()=>{active=false}} , [debouncedSearch,status,page,limit]);
  useEffect(()=>{setPage(1)},[debouncedSearch,status,limit]);

  const toggle=async(key)=>{const next=!settings[key];setBusy(true);try{await updateSecuritySettingsApi({[key]:next});setSettings(s=>({...s,[key]:next}));}catch(e){setError(e?.message||"Unable to update security preference.")}finally{setBusy(false)}};
  const changePassword=async(e)=>{e.preventDefault();setPasswordMsg("");if(password.newPassword.length<8)return setPasswordMsg("New password must contain at least 8 characters.");if(password.newPassword!==password.confirmPassword)return setPasswordMsg("New password and confirmation do not match.");setBusy(true);try{await changeSecurityPasswordApi(password);setPassword({currentPassword:"",newPassword:"",confirmPassword:""});setPasswordMsg("Password changed successfully.");setSettings(s=>({...s,lastPasswordChange:"Just now"}));}catch(e){setPasswordMsg(e?.message||"Unable to change password.")}finally{setBusy(false)}};
  const revoke=async(id)=>{if(!window.confirm("Sign out this device?"))return;setBusy(true);try{await revokeSecuritySessionApi(id);setSessions(x=>x.filter(s=>s.id!==id));}catch(e){setError(e?.message||"Unable to revoke session.")}finally{setBusy(false)}};
  const refresh=()=>{queryClient.invalidateQueries({queryKey:["security"]});load(false)};

  if(loading)return <UserLayout><SecuritySkeleton/></UserLayout>;
  return <UserLayout>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-[#112e52] dark:text-white sm:text-[29px]">Security Settings</h1><p className="mt-1 text-sm text-[#3e5d83] dark:text-slate-400">Protect your account, authentication and withdrawal activity.</p></div><button onClick={refresh} disabled={refreshing||busy} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-[#dce9f7] bg-white px-4 text-xs font-semibold text-[#31557f] shadow-sm disabled:opacity-50 dark:border-[#263752] dark:bg-[#101f38] dark:text-slate-200"><RefreshCw size={15} className={refreshing?"animate-spin":""}/> Refresh</button></div>
    {error&&<div className="mb-4 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-xs text-rose-700"><AlertTriangle size={16}/>{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><SecurityCard icon={<ShieldCheck/>} title="Security Status" value={settings.twoFactorEnabled?"Strong":"Good"} note={settings.twoFactorEnabled?"2FA is enabled":"Enable 2FA for stronger protection"} tone={settings.twoFactorEnabled?"green":"blue"}/><SecurityCard icon={<KeyRound/>} title="Password" value="Protected" note={`Last changed ${settings.lastPasswordChange}`} tone="purple"/><SecurityCard icon={<Mail/>} title="Email Verification" value={settings.emailVerified?"Verified":"Pending"} note="Email identity status" tone="green"/><SecurityCard icon={<Smartphone/>} title="Phone Verification" value={settings.phoneVerified?"Verified":"Pending"} note="Phone identity status" tone="blue"/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <div className="space-y-5">
        <section className="rounded-2xl border border-[#dce9f7] bg-white p-4 shadow-sm dark:border-[#263752] dark:bg-[#101f38] sm:p-5"><SectionTitle icon={<ShieldCheck/>} title="Authentication & Security" description="Manage the security controls used to protect your account."/>
          <SettingRow icon={<ShieldCheck/>} title="Two-factor authentication" description="Require an additional verification code when signing in." enabled={settings.twoFactorEnabled} onToggle={()=>toggle("twoFactorEnabled")} disabled={busy}/>
          <SettingRow icon={<BellRing/>} title="Login alerts" description="Notify you when a new login is detected." enabled={settings.loginAlerts} onToggle={()=>toggle("loginAlerts")} disabled={busy}/>
          <SettingRow icon={<LockKeyhole/>} title="Withdrawal confirmation" description="Require an additional confirmation before withdrawal requests." enabled={settings.withdrawalConfirmation} onToggle={()=>toggle("withdrawalConfirmation")} disabled={busy}/>
          <div className="flex flex-col gap-3 border-t border-slate-100 py-4 last:border-0 dark:border-[#263752] sm:flex-row sm:items-center sm:justify-between"><div><p className="m-0 text-sm font-semibold text-[#17385f] dark:text-white">Session timeout</p><p className="m-0 mt-1 text-xs text-slate-500">Automatically expire inactive sessions.</p></div><Dropdown value={settings.sessionTimeout} onChange={(v)=>{setSettings(s=>({...s,sessionTimeout:v}));updateSecuritySettingsApi({sessionTimeout:v})}} options={[{value:"15 minutes",label:"15 minutes"},{value:"30 minutes",label:"30 minutes"},{value:"1 hour",label:"1 hour"},{value:"4 hours",label:"4 hours"}]}/></div>
        </section>
        <section className="rounded-2xl border border-[#dce9f7] bg-white p-4 shadow-sm dark:border-[#263752] dark:bg-[#101f38] sm:p-5"><SectionTitle icon={<KeyRound/>} title="Password" description="Use a unique password and change it periodically."/><div className="flex flex-col gap-3 rounded-xl bg-slate-50 p-4 dark:bg-[#0d1a2e] sm:flex-row sm:items-center sm:justify-between"><div><p className="m-0 text-sm font-semibold text-[#17385f] dark:text-white">Change your password</p><p className="m-0 mt-1 text-xs text-slate-500">Minimum 8 characters. Never share your password.</p></div><button onClick={()=>setPasswordOpen(true)} className="h-10 rounded-lg bg-blue-600 px-4 text-xs font-semibold text-white hover:bg-blue-700">Change Password</button></div></section>
        <section className="rounded-2xl border border-[#dce9f7] bg-white p-4 shadow-sm dark:border-[#263752] dark:bg-[#101f38] sm:p-5"><SectionTitle icon={<MonitorSmartphone/>} title="Active Sessions" description="Review devices currently signed in to your account."/>{sessions.length?<div className="space-y-3">{sessions.map(s=><div key={s.id} className="flex flex-col gap-3 rounded-xl border border-slate-100 p-3 dark:border-[#263752] sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/10"><MonitorSmartphone size={18}/></div><div className="min-w-0"><p className="m-0 truncate text-sm font-semibold text-[#17385f] dark:text-white">{s.device} {s.current&&<span className="ml-1 rounded-full bg-emerald-50 px-2 py-0.5 text-[9px] text-emerald-700">Current</span>}</p><p className="m-0 mt-1 text-xs text-slate-500">{s.location} · {s.ip} · {s.lastActive}</p></div></div>{!s.current&&<button onClick={()=>revoke(s.id)} disabled={busy} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-lg border border-rose-200 px-3 text-xs font-semibold text-rose-600 hover:bg-rose-50 disabled:opacity-50"><LogOut size={14}/> Sign out</button>}</div>)}</div>:<Empty text="No active sessions found."/>}</section>
      </div>
      <div className="space-y-5"><section className="rounded-2xl border border-[#dce9f7] bg-white p-4 shadow-sm dark:border-[#263752] dark:bg-[#101f38] sm:p-5"><SectionTitle icon={<CheckCircle2/>} title="Verification" description="Your account verification status."/><VerificationRow label="Email" verified={settings.emailVerified}/><VerificationRow label="Phone" verified={settings.phoneVerified}/><VerificationRow label="2FA" verified={settings.twoFactorEnabled}/></section>
      <section className="rounded-2xl border border-[#dce9f7] bg-white p-4 shadow-sm dark:border-[#263752] dark:bg-[#101f38] sm:p-5"><SectionTitle icon={<LockKeyhole/>} title="Security Tips" description="Simple practices to keep your account safer."/><ul className="m-0 space-y-3 pl-4 text-xs leading-5 text-slate-600 dark:text-slate-300"><li>Use a unique password that you do not reuse elsewhere.</li><li>Enable 2FA before making financial transactions.</li><li>Review active sessions and sign out unknown devices.</li><li>Never share OTPs, recovery codes or private keys.</li></ul></section></div>
    </div>
    <section className="mt-5 rounded-2xl border border-[#dce9f7] bg-white shadow-sm dark:border-[#263752] dark:bg-[#101f38]"><div className="border-b border-slate-100 p-4 dark:border-[#263752] sm:p-5"><SectionTitle icon={<ShieldCheck/>} title="Recent Security Activity" description="Read-only security events associated with your account."/></div><div className="flex flex-col gap-2 p-3 sm:flex-row sm:items-center sm:justify-between sm:p-4"><div className="flex h-10 min-w-0 items-center gap-2 rounded-lg border border-slate-200 px-3 dark:border-[#2b3c58]"><Search size={15} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search activity..." className="min-w-0 flex-1 bg-transparent text-xs outline-none dark:text-slate-200"/></div><Dropdown value={status} onChange={v=>setStatus(v)} options={[{value:"all",label:"All Status"},{value:"Success",label:"Success"},{value:"Blocked",label:"Blocked"}]}/></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500 dark:bg-[#0d1a2e]"><tr><th className="px-4 py-3">Action</th><th className="px-4 py-3">Device</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{activity.map(x=><tr key={x.id} className="border-t border-slate-100 dark:border-[#263752]"><td className="px-4 py-3 font-semibold text-slate-700 dark:text-slate-200">{x.action}</td><td className="px-4 py-3 text-slate-500">{x.device}</td><td className="px-4 py-3 text-slate-500">{x.location}</td><td className="px-4 py-3 text-slate-500">{x.date}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${x.status==="Blocked"?"bg-rose-50 text-rose-600":"bg-emerald-50 text-emerald-600"}`}>{x.status}</span></td></tr>)}</tbody></table>{!activity.length&&<Empty text="No security activity found."/>}</div><Pagination page={page} totalPages={totalPages} total={total} limit={limit} onPageChange={setPage}/><div className="flex justify-end border-t border-slate-100 px-4 py-2 dark:border-[#263752]"><Dropdown value={limit} onChange={v=>setLimit(Number(v))} options={[{value:10,label:"10"},{value:20,label:"20"},{value:50,label:"50"}]}/></div></section>
    {passwordOpen&&<PasswordModal password={password} setPassword={setPassword} msg={passwordMsg} busy={busy} onClose={()=>{setPasswordOpen(false);setPasswordMsg("")}} onSubmit={changePassword}/>} 
  </UserLayout>
}

function SecurityCard({icon,title,value,note,tone}){const tones={blue:"bg-blue-50 text-blue-600",green:"bg-emerald-50 text-emerald-600",purple:"bg-purple-50 text-purple-600"};return <div className="rounded-2xl border border-[#dce9f7] bg-white p-4 shadow-sm dark:border-[#263752] dark:bg-[#101f38]"><div className="flex items-start gap-3"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${tones[tone]||tones.blue}`}>{React.cloneElement(icon,{size:19})}</div><div><p className="m-0 text-xs text-slate-500">{title}</p><p className="m-0 mt-1 text-lg font-bold text-[#17385f] dark:text-white">{value}</p><p className="m-0 mt-1 text-[10px] text-slate-400">{note}</p></div></div></div>}
function SectionTitle({icon,title,description}){return <div className="mb-3 flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-blue-50 text-blue-600 dark:bg-blue-500/10">{React.cloneElement(icon,{size:17})}</div><div><h2 className="m-0 text-base font-bold text-[#17385f] dark:text-white">{title}</h2><p className="m-0 mt-1 text-xs text-slate-500">{description}</p></div></div>}
function SettingRow({icon,title,description,enabled,onToggle,disabled}){return <div className="flex items-center justify-between gap-4 border-t border-slate-100 py-4 first:border-t-0 dark:border-[#263752]"><div className="flex min-w-0 items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-50 text-slate-500 dark:bg-[#0d1a2e]">{React.cloneElement(icon,{size:17})}</div><div className="min-w-0"><p className="m-0 text-sm font-semibold text-[#17385f] dark:text-white">{title}</p><p className="m-0 mt-1 text-xs text-slate-500">{description}</p></div></div><button type="button" onClick={onToggle} disabled={disabled} aria-pressed={enabled} className={`relative h-6 w-11 shrink-0 rounded-full transition ${enabled?"bg-blue-600":"bg-slate-300"} disabled:opacity-50`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${enabled?"left-6":"left-1"}`}/></button></div>}
function VerificationRow({label,verified}){return <div className="flex items-center justify-between border-t border-slate-100 py-3 first:border-t-0 dark:border-[#263752]"><span className="text-xs font-semibold text-slate-600 dark:text-slate-300">{label}</span><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-semibold ${verified?"bg-emerald-50 text-emerald-600":"bg-amber-50 text-amber-600"}`}>{verified?<CheckCircle2 size={12}/>:<AlertTriangle size={12}/>} {verified?"Verified":"Not enabled"}</span></div>}
function Empty({text}){return <div className="p-8 text-center text-xs text-slate-400">{text}</div>}
function SecuritySkeleton(){return <div className="animate-pulse"><div className="mb-5 h-10 w-72 rounded-lg bg-slate-200"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-28 rounded-2xl bg-slate-200"/>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="h-[430px] rounded-2xl bg-slate-200"/><div className="h-[430px] rounded-2xl bg-slate-200"/></div><div className="mt-5 h-72 rounded-2xl bg-slate-200"/></div>}
function PasswordModal({password,setPassword,msg,busy,onClose,onSubmit}){return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/50 p-0 sm:items-center sm:p-4"><form onSubmit={onSubmit} className="w-full rounded-t-2xl bg-white p-5 shadow-2xl dark:bg-[#101f38] sm:max-w-md sm:rounded-2xl"><div className="mb-4"><h2 className="m-0 text-lg font-bold text-[#17385f] dark:text-white">Change Password</h2><p className="mt-1 text-xs text-slate-500">Use at least 8 characters and avoid reused passwords.</p></div>{["currentPassword","newPassword","confirmPassword"].map((key)=><label key={key} className="mb-3 block"><span className="mb-1.5 block text-[11px] font-semibold text-slate-600 dark:text-slate-300">{key==="currentPassword"?"Current password":key==="newPassword"?"New password":"Confirm new password"}</span><input required type="password" value={password[key]} onChange={e=>setPassword({...password,[key]:e.target.value})} className="input"/></label>)}{msg&&<p className="mb-3 rounded-lg bg-blue-50 px-3 py-2 text-xs text-blue-700">{msg}</p>}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="h-10 rounded-lg border border-slate-200 px-4 text-xs font-semibold text-slate-600 dark:border-[#2b3c58] dark:text-slate-300">Cancel</button><button disabled={busy} className="h-10 rounded-lg bg-blue-600 px-5 text-xs font-semibold text-white disabled:opacity-50">{busy?"Updating...":"Update Password"}</button></div></form></div>}
