import React, { useMemo, useState } from "react";
import {
  BarChart3, CalendarDays, ChevronLeft, ChevronRight, Download, FileText,
  RefreshCw, Search, TrendingUp, WalletCards, Coins, ArrowDownToLine,
  ArrowUpRight, CircleDollarSign, ReceiptText, X
} from "lucide-react";
import UserLayout from "../../components/user/UserLayout";
import { getUserReportApi, getUserReportByIdApi } from "../../services/user/reportApi";
import { useManualQuery } from "../../hooks/manualQuery";
import { useDebounce } from "../../hooks/useDebounce";

const card="rounded-2xl border border-[#dce9f7] bg-white shadow-sm dark:border-[#223250] dark:bg-[#101f38]";
const input="h-10 rounded-xl border border-[#d9e6f4] bg-white px-3 text-sm text-[#24486f] outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 dark:border-[#263752] dark:bg-[#0d1a2e] dark:text-slate-200";
const typeOptions=["all","investment","deposit","roi","token_payout","buyback","withdrawal"];
const statusOptions=["all","completed","pending","processing","approved","failed","rejected"];
const limitOptions=[10,20,50];
const money=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function Status({value}){const v=String(value||"").toLowerCase();const cls=["completed","approved","credited","reconciled"].includes(v)?"bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400":["failed","rejected"].includes(v)?"bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-400":"bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-400";return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${cls}`}>{value}</span>}
function TypeIcon({type}){const map={investment:[Coins,"text-blue-600 bg-blue-50"],deposit:[WalletCards,"text-cyan-600 bg-cyan-50"],roi:[TrendingUp,"text-purple-600 bg-purple-50"],token_payout:[Coins,"text-amber-600 bg-amber-50"],buyback:[ArrowUpRight,"text-indigo-600 bg-indigo-50"],withdrawal:[ArrowDownToLine,"text-orange-600 bg-orange-50"]};const [I,c]=map[type]||[ReceiptText,"text-slate-600 bg-slate-50"];return <span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${c}`}><I size={17}/></span>}
function labelType(v){return ({investment:"Investment",deposit:"USDT Deposit",roi:"ROI / Profit",token_payout:"Token Payout",buyback:"Buyback",withdrawal:"Withdrawal"}[v]||v)}
function ReportSkeleton(){return <div className="space-y-4">{[1,2,3].map(x=><div key={x} className={`${card} animate-pulse p-5`}><div className="h-5 w-40 rounded bg-slate-200 dark:bg-slate-700"/><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[1,2,3,4].map(y=><div key={y} className="h-16 rounded-xl bg-slate-100 dark:bg-slate-800"/>)}</div></div>)}</div>}
export default function Reports(){
 const [search,setSearch]=useState(""); const q=useDebounce(search,350); const [type,setType]=useState("all"); const [status,setStatus]=useState("all"); const [date,setDate]=useState("all"); const [page,setPage]=useState(1); const [limit,setLimit]=useState(10); const [selected,setSelected]=useState(null);
 const query=useManualQuery({queryKey:["user-reports",q,type,status,date,page,limit],queryFn:({signal})=>getUserReportApi({search:q,type,status,date,page,limit},signal),keepPreviousData:true});
 const data=query.data?.data||{}; const items=data.items||[]; const stats=data.stats||{};
 const reset=()=>{setSearch("");setType("all");setStatus("all");setDate("all");setPage(1)};
 const exportCsv=()=>{const rows=["Date,Type,Reference,Amount,Currency,Status",...items.map(r=>[r.date,labelType(r.type),r.id,r.amount,r.currency,r.status].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))];const blob=new Blob([rows.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`amgp-report-page-${page}.csv`;a.click();URL.revokeObjectURL(url)};
 return <UserLayout><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="m-0 text-2xl font-bold tracking-tight text-[#112e52] dark:text-white sm:text-[29px]">Reports</h1><p className="mt-1 text-sm text-[#3e5d83] dark:text-[#90a5c4]">Review your investments, deposits, ROI, token payouts, buybacks and withdrawals.</p></div><div className="flex gap-2"><button onClick={exportCsv} disabled={!items.length} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5ef] bg-white px-3 text-xs font-semibold text-[#496783] shadow-sm disabled:opacity-50 dark:border-[#263752] dark:bg-[#101f38] dark:text-slate-300"><Download size={15}/> Export CSV</button><button onClick={()=>query.refetch()} disabled={query.isFetching} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-3 text-xs font-semibold text-white hover:bg-blue-700 disabled:opacity-50"><RefreshCw size={15} className={query.isFetching?"animate-spin":""}/> Refresh</button></div></div>
 {query.isPending?<ReportSkeleton/>:<>
 <section className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Total Activity" value={stats.total??0} icon={FileText} tone="blue"/><Stat label="Invested" value={`${money(stats.invested)} USDT`} icon={CircleDollarSign} tone="cyan"/><Stat label="ROI / Profit" value={`${money(stats.roiUsdt)} USDT`} icon={TrendingUp} tone="purple"/><Stat label="Withdrawn" value={`${money(stats.withdrawn)} USDT`} icon={ArrowDownToLine} tone="orange"/></section>
 <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_330px]">
 <section className={`${card} min-w-0 p-4 sm:p-5`}>
  <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="m-0 text-lg font-bold text-[#112f55] dark:text-white">Activity Report</h2><p className="mt-1 text-xs text-[#64809f] dark:text-[#90a5c4]">Read-only financial activity generated from your account records.</p></div><button onClick={reset} className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#dce5ef] px-3 text-xs font-semibold text-[#496783] dark:border-[#263752] dark:text-slate-300"><X size={14}/> Reset</button></div>
  <div className="mb-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-[minmax(180px,1fr)_150px_150px_130px]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search reports..." className={`${input} w-full pl-9`}/></div><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}} className={input}>{typeOptions.map(x=><option key={x} value={x}>{x==="all"?"All Types":labelType(x)}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className={input}>{statusOptions.map(x=><option key={x} value={x}>{x==="all"?"All Status":x}</option>)}</select><select value={date} onChange={e=>{setDate(e.target.value);setPage(1)}} className={input}><option value="all">All Dates</option><option value="today">Today</option><option value="7">Last 7 Days</option><option value="30">Last 30 Days</option></select></div>
  {query.isError?<div className="rounded-xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-600">Unable to load reports. <button onClick={()=>query.refetch()} className="font-bold underline">Try again</button></div>:items.length===0?<div className="grid place-items-center rounded-xl border border-dashed border-[#d8e4f1] py-14 text-center dark:border-[#263752]"><FileText size={28} className="text-slate-400"/><p className="mt-2 text-sm font-semibold text-[#26486d] dark:text-white">No reports found</p><p className="mt-1 text-xs text-slate-500">Try changing the search or filters.</p></div>:<>
  <div className="space-y-2">{items.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="flex w-full items-center gap-3 rounded-xl border border-[#e6edf5] p-3 text-left transition hover:border-blue-200 hover:bg-blue-50/40 dark:border-[#263752] dark:hover:bg-blue-500/5"><TypeIcon type={r.type}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="truncate text-sm font-semibold text-[#163a62] dark:text-white">{r.title||labelType(r.type)}</span><Status value={r.status}/></div><p className="mt-1 truncate text-xs text-[#64809f] dark:text-[#90a5c4]">{r.id} • {r.date}</p></div><div className="hidden text-right sm:block"><strong className="block text-sm text-[#163a62] dark:text-white">{r.amount} {r.currency}</strong><span className="text-[11px] text-slate-400">View details</span></div><ChevronRight size={17} className="shrink-0 text-slate-400"/></button>)}</div>
  <div className="mt-4 flex flex-col gap-3 border-t border-[#e6edf5] pt-4 text-xs text-slate-500 dark:border-[#263752] sm:flex-row sm:items-center sm:justify-between"><span>Showing {items.length} of {data.total||0} reports</span><div className="flex items-center gap-2"><select value={limit} onChange={e=>{setLimit(Number(e.target.value));setPage(1)}} className="h-9 rounded-lg border border-[#d9e6f4] bg-white px-2 text-xs dark:border-[#263752] dark:bg-[#101f38] dark:text-slate-200">{limitOptions.map(x=><option key={x}>{x}</option>)}</select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="grid h-9 w-9 place-items-center rounded-lg border disabled:opacity-40"><ChevronLeft size={15}/></button><span className="font-semibold text-[#23496f] dark:text-white">{page} / {data.totalPages||1}</span><button disabled={page>=(data.totalPages||1)} onClick={()=>setPage(p=>p+1)} className="grid h-9 w-9 place-items-center rounded-lg border disabled:opacity-40"><ChevronRight size={15}/></button></div></div>
  </>}
 </section>
 <aside className="space-y-5"><section className={`${card} p-5`}><h3 className="m-0 text-base font-bold text-[#112f55] dark:text-white">Report Breakdown</h3><div className="mt-4 space-y-3">{(stats.breakdown||[]).map(x=><div key={x.type}><div className="mb-1 flex justify-between text-xs"><span className="text-[#496783] dark:text-slate-300">{labelType(x.type)}</span><b className="text-[#163a62] dark:text-white">{x.count}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-blue-500" style={{width:`${x.percent}%`}}/></div></div>)}</div></section><section className={`${card} p-5`}><h3 className="m-0 text-base font-bold text-[#112f55] dark:text-white">Date Range</h3><div className="mt-3 flex items-center gap-2 rounded-xl bg-[#f7faff] p-3 text-xs text-[#496783] dark:bg-[#0d1a2e] dark:text-slate-300"><CalendarDays size={16}/> {stats.range||"All available account activity"}</div><p className="mt-3 text-[11px] leading-5 text-slate-500">Reports are informational summaries. Historical financial records remain read-only.</p></section></aside>
 </div></>}
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" onMouseDown={()=>setSelected(null)}><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl dark:bg-[#101f38]" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><h3 className="m-0 text-lg font-bold text-[#112f55] dark:text-white">Report Details</h3><p className="mt-1 text-xs text-slate-500">{selected.id}</p></div><button onClick={()=>setSelected(null)} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-slate-100 dark:hover:bg-white/10"><X size={18}/></button></div><dl className="mt-5 grid grid-cols-2 gap-3">{[["Type",labelType(selected.type)],["Status",selected.status],["Amount",`${selected.amount} ${selected.currency}`],["Date",selected.date],["Reference",selected.id],["Description",selected.description||"Account activity"]].map(([a,b])=><div key={a} className="rounded-xl border border-[#e4ebf4] p-3 dark:border-[#263752]"><dt className="text-[11px] text-slate-500">{a}</dt><dd className="mt-1 break-words text-sm font-semibold text-[#163a62] dark:text-white">{b}</dd></div>)}</dl></div></div>}
 </UserLayout>
}
function Stat({label,value,icon:Icon,tone}){const tones={blue:"bg-blue-50 text-blue-600",cyan:"bg-cyan-50 text-cyan-600",purple:"bg-purple-50 text-purple-600",orange:"bg-orange-50 text-orange-600"};return <div className={`${card} p-4`}><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tones[tone]}`}><Icon size={18}/></span><div className="min-w-0"><p className="m-0 text-xs text-slate-500">{label}</p><p className="m-0 mt-1 truncate text-lg font-bold text-[#163a62] dark:text-white">{value}</p></div></div></div>}
